### ISSUE TITLE
Got problem while running on my local server

### ISSUE THREAD

**Issue by HEKntg** [mutalyzer/mutalyzer#480]
Hi,
I have deployed mutalyzer on my own local server, but I got problem while using JSON api...
`kcuser@ubuntu:/BIN/mutalyzer$ mutalyzer-service-json 
Listening on http://127.0.0.1:8082/`
That seems ok.
Then I use python `requests` to get data: `url = 'http://127.0.0.1:8082/runMutalyzerLight?variant=NM_005228.4:c.2296_2297insTGGCCAGCG`
I got this:
`ERROR:spyne.application.server:Error 111 connecting to localhost:6379. Connection refused.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyne/application.py", line 151, in process_request
    ctx.out_object = self.call_wrapper(ctx)
  File "/usr/local/lib/python2.7/dist-packages/spyne/application.py", line 235, in call_wrapper
    retval = ctx.descriptor.service_class.call_wrapper(ctx)
  File "/usr/local/lib/python2.7/dist-packages/spyne/service.py", line 207, in call_wrapper
    return ctx.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/mutalyzer-2.0.31.dev0-py2.7.egg/mutalyzer/services/rpc.py", line 1216, in runMutalyzerLight
    stats.increment_counter('name-checker/webservice')
  File "/usr/local/lib/python2.7/dist-packages/mutalyzer-2.0.31.dev0-py2.7.egg/mutalyzer/stats.py", line 50, in increment_counter
    pipe.execute()
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2556, in _execute_pipeline
    connection.send_packed_command(all_cmds)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
127.0.0.1 - - [29/Jul/2019 16:53:05] "GET /runMutalyzerLight?variant=NM_005228.4:c.2296_2297insTGGCCAGCG HTTP/1.1" 500 56`

What should I do ?

**Comment by HEKntg** [comment]
I finally solved it after installing `redis-server`.
Sorry for interrupting you...
