### ISSUE TITLE
Error in normalizer: UnknownSeq is deprecated in biopython 1.81

### ISSUE THREAD

**Issue by flashlab** [mutalyzer/mutalyzer#79]
The demo command `mutalyzer_normalizer "NG_012337.1(NM_003002.2):c.274G>T"` output the following error messages:
```
Traceback (most recent call last):
  File "/home/zzbd/.local/bin/mutalyzer_normalizer", line 5, in <module>
    from mutalyzer.cli import main
  File "/home/zzbd/.local/lib/python3.7/site-packages/mutalyzer/cli.py", line 4, in <module>
    from mutalyzer.normalizer import normalize
  File "/home/zzbd/.local/lib/python3.7/site-packages/mutalyzer/normalizer.py", line 3, in <module>
    from .description import Description
  File "/home/zzbd/.local/lib/python3.7/site-packages/mutalyzer/description.py", line 12, in <module>
    from mutalyzer_retriever.reference import (
  File "/home/zzbd/.local/lib/python3.7/site-packages/mutalyzer_retriever/__init__.py", line 3, in <module>
    from .retriever import retrieve_model, retrieve_raw
  File "/home/zzbd/.local/lib/python3.7/site-packages/mutalyzer_retriever/retriever.py", line 8, in <module>
    from . import parser
  File "/home/zzbd/.local/lib/python3.7/site-packages/mutalyzer_retriever/parser.py", line 1, in <module>
    from .parsers import fasta, gff3, lrg
  File "/home/zzbd/.local/lib/python3.7/site-packages/mutalyzer_retriever/parsers/gff3.py", line 37, in <module>
    from BCBio.GFF import GFFParser
  File "/home/zzbd/.local/lib/python3.7/site-packages/BCBio/GFF/__init__.py", line 3, in <module>
    from BCBio.GFF.GFFParser import GFFParser, DiscoGFFParser, GFFExaminer, parse, parse_simple
  File "/home/zzbd/.local/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 34, in <module>
    from Bio.Seq import UnknownSeq
ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq' (/home/zzbd/.local/lib/python3.7/site-packages/Bio/Seq.py)
```
Seems the same issue in https://github.com/chapmanb/bcbb/issues/136

**Comment by mihailefter** [comment]
Fixed with [1](https://github.com/mutalyzer/retriever/commit/7c09f80807ef9e93cbecfe3968d608fcf0c47b3b) and [2](https://github.com/mutalyzer/mutalyzer/commit/fce8fa075ead1bb17e78104ae989b0fb3def0b07).
